services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 2m
