services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI
    restart: always
    healthcheck: ["CMD", "curl", "http://localhost:3000"]
    interval: 1m30s
    timeout: 10s
    retries: 3
    start_period: 2m
